apiVersion: v1
items:
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: enmasse-address-admin
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - create
    - delete
    - list
    - get
    - watch
    - update
    - patch
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: enmasse-admin
  rules:
  - apiGroups:
    - ''
    - project.openshift.io
    - authentication.k8s.io
    - authorization.k8s.io
    resources:
    - projectrequests
    - localsubjectaccessreviews
    - tokenreviews
    verbs:
    - create
kind: List
