---
- name: Deploy the address controller
  shell: oc process -f {{ playbook_dir }}/templates/enmasse.yaml ENABLE_RBAC={{ enable_rbac }} ADDRESS_CONTROLLER_CERT_SECRET=address-controller-cert ENVIRONMENT={{ enmasse_environment }} | oc apply -n {{ namespace }} -f -


