apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iotconfigs.iot.enmasse.io
  labels:
    app: enmasse
spec:
  group: iot.enmasse.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: IoTConfig
    plural: iotconfigs
    singular: iotconfig
    shortNames:
    - icfg
    categories:
    - enmasse
  additionalPrinterColumns:
  - name: Phase
    type: string
    description: Phase of the IoT config
    JSONPath: .status.phase
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: IoTConfig deploys the IoT protocol adapters, device registry and tenant management services. This resource is created by the service administrator.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
              pattern: "^default$"
        spec:
          type: object
        status:
          type: object
