apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iotprojects.iot.enmasse.io
  labels:
    app: enmasse
    enmasse-component: iot
spec:
  group: iot.enmasse.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: IoTProject
    plural: iotprojects
    singular: iotproject
    shortNames:
    - itp
    categories:
    - enmasse
  additionalPrinterColumns:
  - name: IoT tenant
    type: string
    description: The name of the IoT tenant
    JSONPath: .status.tenantName
  - name: Downstream Host
    type: string
    description: The endpoint host name
    JSONPath: .status.downstreamEndpoint.host
  - name: Downstream Port
    type: integer
    description: The endpoint port number
    JSONPath: .status.downstreamEndpoint.port
  - name: TLS
    type: boolean
    description: If TLS is enabled
    JSONPath: .status.downstreamEndpoint.tls
  - name: Phase
    type: string
    description: Phase of the IoT project
    JSONPath: .status.phase
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: IoTProject creates a new isolated space for IoT related messsaging. This resource is created by the messaging tenant and is also sometimes called an "IoT Tenant".
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        spec:
          type: object
        status:
          type: object
