apiVersion: v1
kind: Secret
metadata:
  name: infinispan-identities
  labels:
    app.kubernetes.io/name: infinispan
    app.kubernetes.io/instance: infinispan-1
type: Opaque
stringData:
  management-users.properties: |
    admin=test1234
  management-groups.properties: |
    admin=admin
  users.properties: |
    app=test12
  groups.properties: |
    app=adapter
