apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: infinispan
    app.kubernetes.io/instance: infinispan-1
  name: infinispan-jgroups # align with "jgroups.dns.query" in statefulset
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 7800
    targetPort: jgroups
    name: jgroups
  selector:
    app.kubernetes.io/name: infinispan
    app.kubernetes.io/instance: infinispan-1
