apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: enmasse-sub
  namespace: ${OPERATOR_NAMESPACE}
  labels:
    app: enmasse
spec:
  name: enmasse
  source: enmasse-source
  sourceNamespace: ${OPERATOR_NAMESPACE}
  startingCSV: enmasse.${OLM_VERSION}
  channel: alpha
