language: ruby
notifications:
  email: false
rvm:
- 2.2
script:
- make
after_success:
- curl -s https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master/trigger-travis.sh
  | bash /dev/stdin
env:
  global:
    secure: AsrU/VbVvXQyhFpL0cumYC4olghWOf+zCRgBu3sg+Ozx9LRF/4ikBECuh1DWvXMmxmUbWrDDTeIlYPgc8Wz7/Nzic5dZ8K2SFLJsWu+LKHriVsQcWuL9PRmh80PfSos0ouMK0L3LYXIVnilGE1b+uJmRDXRGAxCkcGZUObOgBUiwKduxFpZbwwr/nvibsQxUZ12VEDZooh7b1yOCv8t7E4WJo1kGxCGNaZqq9PfebwLmposLib2SyAWb/HpzV75yd4y6z5OOUUEGHIMZJl3t4iM08U+fQj2iAax+uEoy+bu7r7yD5macRSfoOZH8Y/EPrQk/0b2Y70qN2PYbeHNp4uj67snVRVcVLTFjFNzSY840Aq/uKg2tmFqIhWBdgrjnSxrYcRZG15Szfx35jLnFts0kkrKP/9Uw/XqcUwNVbsETq5WzIilSu12UtTcPp2OO/coIiHyZQ7ub0Zwolsdmrg0OE14cSGuc79RulOP6KpxJfizkP9erWilnYLHTdDd/8IAkBwDdelLqpgIBS8dbQXVkJGvH505HO3mbUeXg2IdEdl1Ba9BK8Y0DbehmjjjJcichEkFLgFB0av2sIiuO7PmO+CKHYvAu4keykdPSwAsk8fknAur5K3uLfMz+TdS5zQoP5NAx5FtOa+ynwEgtsEZRa0C4Yph7wDs4B45Dfyw=
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HepZcALZznJ9XL1gumw4EqtG2doiWX+dEdUy0Qug+DcFM6mTb7m61YIrYmiw0h2FCqzozsSjlDjKfBLUgnUalj6f6LZCQKqThh04VKQoBmDJbUoOX7nSiaGeV9SJ18zeG8MrIkoHriJVGnfKUTL870RSQGzRvCXOUyQdx9gy/kfFFM4R9eUN8XOH/nMdmMhtoqwlhfjcY8T0qeKlCISqFCXlan+uIV7KERVSiiBdK4L4fsA5VB8Dd3SUHKe2zpcntowsBXfGI9wemWe++FysZ4Wsg+bBohiZ11A2xeHWCpswosvUHl8OcRyQDK5RqLsphdhTcFxaKvuyXl8v0eecg4ktdHkVQ0EbEauTtd/19lDa4oNpv/Thm3ElKpM77xq4gf0CLW/QNCO6OSQ9zPKughyaH3b/lseLWvVxYEKsPanRdYCZO0PjVOUGtbUpPRxP5CkNDEkW7mpfbK0IgxAemGy0mcTnSWFKQOgdB9iyiZA+lrHdrF9pc1rj5QPbDE8e7mn7FoosPsZuwGjZAb/7lBdZ4aerUXHHsBoyRrVEMvj1qABv9UJtokgo3rBoY/JGdHX9Rq9gsVVQeLLFir5EIFlsTXoaj4z+NvwC5ODklNdBoQvkXYzZ6z9OYsCGDjl09rFi7AbMXCM7nLeKzUv3XQbuEr9iHHpkWhKO8gc8hNw=
  file:
  - generated/enmasse-template.yaml
  - generated/tls-enmasse-template.yaml
  - generated/enmasse-kubernetes.yaml
  - generated/enmasse-template-with-kafka.yaml
  - generated/tls-enmasse-template-with-kafka.yaml
  - generated/sasldb-enmasse-template.yaml
  - generated/sasldb-tls-enmasse-template.yaml
  - scripts/enmasse-deploy.sh
  on:
    tags: true
    repo: EnMasseProject/enmasse
