sudo: required
language: node_js
notifications:
  email: false
node_js:
- '0.12'
services:
- docker
script:
- make

after_success:
- curl -s https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master/docker-build.sh
  | bash /dev/stdin enmasseproject/ragent .
- curl -s https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master/trigger-travis.sh
  | bash /dev/stdin
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: nwjqHuz72ZCgH7GfAf1ai/uWi2TGG+C1SeAnQklOKne3ClKPcr0I34fByZOi8J3n6h6VpM9NpuDruz526IMwvhi7SnmSjsNWpIE+TukpA+V5PLelpkG65mKS7C+JcolxPO04xLpwneeJFV+PIuihaYsBQT03AWFD3wRqcNiOR0iN0Et3HwXQ7CG9XUSlZCJM1y8xJwWzOQkQB19MsIHKi+nl0FxhCB6Ijh/DS1c65524uOL+XMww8oUr6E02JzriNsXeozIyD6zfCWBQOxR/EedqhSRGGlglommQt5suQZgd/F3ld57JGlokvdltdKSHHfdarAOgxa8Rh4csrPcCrMu6uryLWoavprP8jtCku7XNUjEaLrjfom+NQy9x+aX4bI+AgjyXp9zZrrx1AfpaKxwMn1ej8rkW9LlQc48j4WNMubWq1LMUbjJe/KLRsBlTQyi6ff0pYpwlilCRMm+0DwygRuMX5QFS8ZzIiVrjRoDTD83VlqfaCGGkTSLbmNowxe2uzqgkEcDWyjpMXUxd58kn3SZQktk0v8IpzM8akAVO9XRDaJwWIhMPZiUYCI99IXDcyOtH9bsieMkVany4kDkH55PrkeII4WdGeRkz+EiPaeWEliCQZypXtAK0cuFt27fMuxOTA+WTmoTBzrX5McSizG7sulVyys4cat+i69g=
  - secure: S9bA795E2z9kCyvU2rCKALll8Qg9j8M95VbGge52LWyePAluvuDdqmX5LAMRarYEMdVsq60reFH1aphWoZjEtdU0wV4Whf18j7U2aTgN8V2Tcq776+wgYAiS6a/mUThbs36gdV8cimHGr2/ksaj4sYON9g9M7HZJlVuX6ZE5bLLpRejZNKAA5bPGgwINI/zQJ3wOHzjH454YigZMnnwwdu89ot26yOx/5bHoHZTflrpVFO0ogO8/VuS59v4eFm7v6z+46XMuEB76hfX9v4I3qUe7m4LYaAxxWXvyVpfHDjjCSkg48YJ2Gi+HI8v3LhrKYMmlpAHnf1M3GMZXZGZb0o1wl2Pg3xmzjc81oimCljA9Ia88Ip3yMPmj7weozNhFs6+NfpKReE75I7ynLc8ecY5SnnlyfgtwcRo+sBDIWbbUrAh8wPx6+fc+eNQ0tCYtxdWCYR48udWRotX2TjuedwXcwKxOpw8TNt5oFhBh5fDuN4BmKrFrtAjfup6Mp8wme2hjU4z/k9vH3J3NyRfb6sPV0wAW75CdzI7BjlOllZcyvMA2q4SlU7ew7mEfhyvlwX7gpSZRYLek4+OKB8sernPPirrfUzqPLb+zoelU0s3vaxkRS/EeLF8Vxd1zKtvq3EJgKph8jWWhR/5rwdbrTTcmmAYoVGjstIg8HxsfFy0=
  - secure: WWtwrQTKPb9cjpKJgCnGA4eUOr3Fyh3M7KlXVJZ+8EQJ+SLNfjBG88a5L4SNStMkXftru1RqQnGF/WYJHej3c2BP8fMExldkR1BATVaffBESri/qSSxcFHQP8t2cZ7mM3TesWdwqy2V/ajRdxFblCFYfxKjdg10xb++82HEBCcXk/eYoPRbRGaUFgE6fxfNxI3dD2zUIt8nyEu6tXkWlHdTLgZcfjfPgijZDFveEFdiuo6m8hWG9IK9WZRn2v89ceoVRk+VxZYiu2juQkG9jU2WmSgE0ofhC4uiMt5vFER04/vpQ6jaGbMxnO1O+9kYPrRU2JbsZFk2u2UcUdZlWoOBuF6o8m8JEFRuzCEEbOf4e6qjIzO70Mw17TEmzTj3rGbwCffkme1sDCA/khYc6LUN6MFWLDFzEwNqn0fLMtSl0BNkTqeNjZNPd4/BRP8pzi6BwhWO6P0XLtHOcm3zfHe5X3Fago2jApGUOGNMCBKv8pwCpi4CAp89GDRDomZG5SSakRs+oqvUYsTGgO32j9X/cb+9m8fS4TWnefL82ApG6Ub3jEm1JueDerwz82FsdjH1LrRkpl8A84tSJZQNGHKz+J+4pPBX6372DMu6Pr3Fw2FqsyZ0ZHF4CtlWQ75VcM91sYsjWlYKLSBTEP0Oo7o3Wn53jHlzHZQQmqL4WCs8=
