sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
notifications:
  email: false
script:
- gradle check
- curl -s https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master/docker-build.sh
  | bash /dev/stdin enmasseproject/address-controller address-controller/server
- curl -s https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master/docker-build.sh
  | bash /dev/stdin enmasseproject/configserv configserv
- curl -s https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master/docker-build.sh
  | bash /dev/stdin enmasseproject/queue-scheduler queue-scheduler
after_success:
- curl -s https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master/trigger-travis.sh
  | bash /dev/stdin
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: pdYUIqs3YYtpDu3leNYV/T6H8rCfocCGEYL0wsy2N2W+PwGyQyV7h48pg3C+wL5cN1mNEuNEEFGkFvSlvt5XW+bP4u2ypQGQf2SSeEDTB/NEx18nDkWwGYxq79EcDeAriqbQCvO3GLyT5Uheh5/6A54Hg/qq6VnDptyN9AIhihKWms6OF9Y8lTKKPjBlIyvYXDNbYG8ths1WszBPCa1MJO+C/fhT0RkyxQz5y//pDU9FD/q9bIlN+bxTLZT9TFZKkiUaxVwreBJLNBnfOjbdBCzp4p0K4OQNB3ORZxjKiZowCuN4Rj29D6LW6vcy4+gOjbILlFzewgouCUJ7Q9wL9g5ypPAIZMbnKYUwdUi9niCmpdY1qJyC0GjCbI4yH0KOep114O6pOappAKOoXzoE+41yCb9Nh3TjYxlP+MwO6C4rMjsZclh+9gdm1uIF2yEkd23HwNWfwUXLJSO6cnnRSDaO+psS9E/jKUh4aVdClA+wG5eVJ2OS13At15909WI9MTFf3fwazjLancgEaEL7SqxJ1nBUEzoFSD7wnOY/T69IZHnvOnzWrHku1INrX3kdYH0u9Zi5JoaC4g40y8kG0jhaFJxPPGLiTs5HNLYKK1ka9KvN5gGCrb4Ca5e7ftDqcDt7XtqNNkgp4kXsFxUQ8Y31RCEZe+zJnwQ7oZQW75g=
  - secure: iV+3xS7j/e1yLiniUDYb5W+oF9pvmjdqAgQY+9E8U55UYycMiFMruJ8uBoyb02lPVp9Qa5VL02e4Lfax8Kdfr6zLqOFuWSVnAwk9a5m58LtYfLxKKHgK+u6hr4ABmt9vPOqRa5gOlzMNVAYZdOEKewdqOaC8pCQnxT7/Amdinq6/eLoMUpYjhZtG7Qb/OrPhqTXLPezzmyfbkG9MG410Ek6HMu+prfMJkXAg6Q1I5xlBypoSp/qMxuO09KP8DNYNpUS5n85tS+7GivAKxq1OBf431OqeZaFGpcJH2HXuVtQLlf7DtBwgGYWnvZNpRpXfCi63XzX2f3eOfFnKzEOA8x/OCO7xqGHjmjvNUfhjewz3T+TGU2lfPZV7yIhC7h/C3gD0lIe+7cXMAFSbsPUUrVdI6eVpvp79n2yec+zmtRJS5zqwOdVXP3kNQOlOmf4QVk2VN8L5TKoYX9sFyGHmGc+CDj5ZRNe3/6Z7Rfh9WwpoEusBE+L2rH2CVEuU0MK6kZByvl4TkEQ0ylfKHSaALd29VUblqKZAbgr2zfibGpwmGdqvaJK4fB7wLkJ+of0nHmvC8wLN4Z8h9hYXbsoRq27R6Atd6mVtPb5A8fE/HefqsvGkYDe1aRUh/yzSTKuWgQl+XlmesDZ2q16+fwMk++Rfkoop3qRh1a1qakBPY9Q=
  - secure: FJzlJCCif38TrkFGFtEecQ72kHWn7GW9u8NaCah0Q0uWGJXDujhiQ4vpka+xuAnzows3VXVf8jnXEiRcscEET4lyeZk8e/jrLuLvFrae+iH4fNMTp80Lt+R8UCd0rCKJfV9v+avS3wFwlYLuvzixVdu6jOXaOF9ocYBozDOIP69Nf90fpRomwERD4p4iSWn25E+t2hycrt/9nL+bCgPUSHyPLIsDS5lM4vJM8iBPQR3hDlt9hcAdq9tvUcaa307qja7suTp4KkBJQkPCZn9QIAQ6Ad+aytRZGCFmgqqf3cauGI7cLiigIQ+HG4BFMLKRaIa2uRcOL7jrw8sT89XE5Ro6Phxbku2feysYAxY2X1PiSHf+0Ig6TO+fA4wWY99jWQAE3p0ZshcKECvcxXcjfToS79q82MBfMQQ673pci2IPRZLxb0j5z4/ciaIPkig0KSj7KDlLYqk8L30VnFo8sUzSuZk9mSLmKfZ3dSH79psY1pBR1phBlEfV6M9zolEIhljYZTy+PGLwnnPmCss2M5o0t06hxHAT0EvzhCg5tv5X/pV+LeAw8Uicjf9K+UMc7B9HA+FYuvtU0CCIOTRAd/TYjoK6gdc+XJRqJJvIdoUKEs2VXeFWOS3+iRREnh/sf77tHj07YfjLcF2Pom3vGDS0dJ/Inx8rJof8hHEabZ8=
