language: java
notifications:
  email: false
  irc:
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    channels:
    - chat.freenode.net#enmasse
    use_notice: true
    skip_join: true
sudo: required
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
before_script:
- ./systemtests/scripts/install_openshift.sh /tmp/openshift
- ./systemtests/scripts/start_openshift.sh /tmp/openshift
script:
- export TAG=${TRAVIS_TAG:-latest}
- export VERSION=${TRAVIS_TAG:-latest}
- ./gradlew clean build pack buildImage tagImage pushImage -i
- cd systemtests && ./scripts/run_test_component.sh ../templates/install
after_failure:
- cd systemtests && bash ./scripts/print_logs.sh /tmp/openshift
after_success:
- ./gradlew tagVersion pushVersion
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - SCRIPTS=https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master
  - secure: x+tvxuIjSuZKLO4iO+/kqMb6RUqU7phvjV1RRQNXmAWqIBTq0cxtA4TyadUhlPazUDZLNKGEXW4EHTr7f2YwKefWKQHyZ6FhQcdb8lv8M9GAxDzRtalDh+/tip2yyZgBDakQwDytH0Dsiuh+kFuvIGCBagLesDNaMWxM7jc0E/qFNfrmJDu+jYw5SkwMzAqGeXIcWHE5Ry0iDqMz3k9A/L4vfJaKYK8axV/TJhVqCQu+L5ZLb091nj8VKigSZ89kukn14y4WhKdcf0rc1eS8fbrXrw6Vq9TXszSUVDv6lrT5ehHPVRCh2LQLpuT66hbQM/2mvysMcbWM1QH8shbUZbaCXKCB7GAfwlEkbzVQ0nBNvX7GJ32yzxRKNxr5X9O7UG9uKEC/nO3xjXp6yaFlBwC6ymAa5uwvGL6GjC5Kt5WRvrMFUncRwfEFGs3yTWSu7O5plY3KEYt0vV0quaqEZ+m7s++j6v1FxFv3izzC9IlrsJWPGxe+9ZFUkgaYkDqs6bMqXnLIQ7GF6KvWMETiXnCBdCZH68Up76oIybqmPH9kzUINi2fy1amI28oOlEi3neFncYAojzW4l7eRk7p0xGwTAucsEfUl+MsK+xiw03wquAWCuvMp8exga2ophaTZLYC2Pv+LEt4TP/clzmbTxV8qi2jQ9LBwA3R2CAdfz+s=
  - secure: lnT2MgoFqYw2ewqspLwSzFQ0HqbbBa5nGGctlg8YaaYYY/J1aS5QO3054mjCdCMKygIgFndbiFGhbUIjEpjcFBUjEQraZ70VRnx6kKSU5RehNVhgRu+fXpZ3HCZttxsXJ8a8APN9l7hvsdLNYdkRrOmqojMPGRA36kpSn46Zb6i0jUJt+sRUAeXrCeIznGgSOhpkPUE9xgBIvbQM2adQmrKDmaCwImagyGN1sC8TmOCBTJHJ3imaS3EhZ9koVFvrbBws/oAj/3jYsl3JV1GyuxVHJQD0KLDekMXp5rvOsaclPLUR1SJzqL5Lf+e4YJM+/XCRHK+FUTq60+YX+6FlyQDU5E2671r5DgZwwLYypOBN8YffUBHY7K0n71rrkAghlvdpob30H3Lxh7r40hzwY4Jvu2gFn9JJUgvPOvw5R85y4Jeb3OqmhQu+k96hNB8JvoC0ow6RCSPCOlhovh2S1mEljL8i/etJNmdFqsumoVK/0BUB1iKgR93WOFUyjMjMW1Jdg7KQ4JvDLW01zmzQZ53Y4V720BeYFLITtuL+VTdRWEuR+NlrqDSnb6QGWU6xTiaDwzacn+7RdNwCMlf9FzKryn2uttVWescPgDZlIYQ/vbimZSIboBA+2fjbqJeCiP0Unkvq45Jibw4bbdZ5uqOqMRCddc4B/0Xp04VpKF8=
  - secure: kXUbI3I1Y5+gRS3kDQDtzv/gzIPnGaGy/4WrMR0isCFAoojiXiXjvgo7jwluApvrwVexN4sEGXseRN0eCV/Iha3di/JnDmSC76QM/KnZKcoOCf6MXjaMd+Hpe7hESRsHGrcjmpzELvpXKKiicz5GfLGA8kPCvuK42/6McZGhPKQOA6Q62KH5tw4sqM6XYA8hiqGQc8Av99mUjGwWJyI5XX0VNpcmQTz4JHYkIDZFAYArXUZ+uwo6l7JvyYxp1mup/ooAX14NEt5nhaJY/1CzIHsQdlNxvCsvqp+qgctfjAOyAMh6I5klInEKu+GZVHA8cIu630MNP7O/qHTQMZ78i28EiFhkG2POTATz3gAmpoVTyk7l77NSGDpCYOVB5WbkCq3yUNO6c6xblyhkOsJOwJCdtE8BfzCbL/sacqM6LU8qTRxadUvdMYRA9M+Ag+yBfYMivkJNp6NlSXH6S6K/XnCUIH80T/4dZQ3Zm7LlmL7Iia2FH6AOic8U7s+WdVMzvK3AOcpqfKDoR+usl3UQKqdNy4LVNGhhuyJWgEJ12NgXEGdPubntssSfN3cdGWLeEUrV48hPoLY+bf89lcacmlttq867c5XWuUUABuhM+cwmuJ8+mu83QhWzS/vdc0H1xT1pKpLpO3Gs7/vo/PZSP3t/hRC6+WNARX/6NbCpbsE=
  - secure: b0itSkfj0fvBPAhQW3Is1AJX1XRnEOWCcGBP2aY81Fk0l4gpVFjrNXnQeoH6Wqcrz0B9kdOs/TjjcGfTEnu3UABAdN4pHEp3c/SL3WrlEfcfoLax4T4ul2Ms6Elr8Zx7pRNuPGClpquHhx+pJyJ3/Q+TKs2PdeIP3KnPJYZpy/Ui+8qpdkVY9hrdN4yLKv3CV+AnTjAFu+Ss9B51kVPrXwTNDDaYZtON+HawVpFIvEzfkIOfiwK5+lb5Wc70jU4MKIFXZDoZVVYpq7cbOm/kWpAyfZ4iwf9f5pAknwIK8H+mTG2h3iaG4Xv1WSal7lqRt19aEdOuAjdt4xJ8y7cln8v+csJ9M6Ok1eR3lzBfDCxQTcwOXFmW41fbSw3fCKBZLPXhp044qtRjawkmKZFkU3y3IdLEWOY0xudCRNGN9tq4JXwDppyhrTredojSbVSolAwhArSvzVzksplQZPm5az8OvnhXxF5O9+kY60wcFzLeTS+09PV69iBeDLESoDHcF4z6FUUL1/53SvSgUsXGb3HYdg6JFnLi1ZafHtdionBy9akak14i2PTeHXJmvVZFQ7E5np0pe0lHD7oMqfwPOEuHWvcJmAUDvpv9sIkzyaDCJckZpJ9Te7/gDjopFIlUU4hn0IueMKZA7t26dAy7fpLC/yKnTsja4mzLRYiSgbs=
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: HepZcALZznJ9XL1gumw4EqtG2doiWX+dEdUy0Qug+DcFM6mTb7m61YIrYmiw0h2FCqzozsSjlDjKfBLUgnUalj6f6LZCQKqThh04VKQoBmDJbUoOX7nSiaGeV9SJ18zeG8MrIkoHriJVGnfKUTL870RSQGzRvCXOUyQdx9gy/kfFFM4R9eUN8XOH/nMdmMhtoqwlhfjcY8T0qeKlCISqFCXlan+uIV7KERVSiiBdK4L4fsA5VB8Dd3SUHKe2zpcntowsBXfGI9wemWe++FysZ4Wsg+bBohiZ11A2xeHWCpswosvUHl8OcRyQDK5RqLsphdhTcFxaKvuyXl8v0eecg4ktdHkVQ0EbEauTtd/19lDa4oNpv/Thm3ElKpM77xq4gf0CLW/QNCO6OSQ9zPKughyaH3b/lseLWvVxYEKsPanRdYCZO0PjVOUGtbUpPRxP5CkNDEkW7mpfbK0IgxAemGy0mcTnSWFKQOgdB9iyiZA+lrHdrF9pc1rj5QPbDE8e7mn7FoosPsZuwGjZAb/7lBdZ4aerUXHHsBoyRrVEMvj1qABv9UJtokgo3rBoY/JGdHX9Rq9gsVVQeLLFir5EIFlsTXoaj4z+NvwC5ODklNdBoQvkXYzZ6z9OYsCGDjl09rFi7AbMXCM7nLeKzUv3XQbuEr9iHHpkWhKO8gc8hNw=
  file:
  - enmasse-${TAG}.tar.gz
  on:
    tags: true
    repo: EnMasseProject/enmasse
- provider: bintray
  file: ".bintray.json"
  user: "${BINTRAY_API_USER}"
  on:
    tags: true
  key:
    secure: Ah+rCOJtb6z/ZEwXaZ2buHNbVSIAYkFFOGyaC6hYrpIHixg0c3PviHxuYzuvZehHtnmzlFhDFwvsfvkY7fbqIIgMuGG5VECHfVcI/krGWCrWbQjfePEI6cyvva+wRDBhQPtUe0UVd55Uc9jn2W4mzsEc7de2FD+pEs8kbu0WwUWANwpOJmmqeU8xbDjfPNH68djw5pqrC8XUglCQXgAPKbSDdorhm3WLh8cEMG9tfZJvXb3aILB6/TMkIQ5mTacdOw5czD5AaMFCFrRQ9zP6va1gnVL4w1E4wrOH3j4um9isl10FRQ6ULliUz5XwubwhBobJR5CDGEuVTqQtDD3XzpmgIX3attY9OayS9J1Yph4QAv/YZLR/mGnPZSRf5QHfHrZUl2I947VazJvrl77Z3e2t/q2gFBqZBlqvBrUEDUiwofZAhQ3uWe1bo6F+CjCO/0HBwkjDrLYqqv/UN1vciXLStE/K4HLq6Zh+t3NOx9BdmsXmyCPWMkzM1h6Lpgf3qSsKP+ygctlMIpqwkqoexvw7O/s0fS+FBLlQqUeNCAVrci/NXc9LpQF/3LeoRyTKLxoIB7m5klzWzXRRV/QdieH9mX2OJ4BX3E1uT+4dfkSy7fh3JImRvZ0meMNTSsHUiHoVBFvUIfnuchu6g9lYV/7Vevvy6O1yzjZIHPXYscI=
- provider: bintray
  file: ".bintray.json"
  user: "${BINTRAY_API_USER}"
  key:
    secure: Ah+rCOJtb6z/ZEwXaZ2buHNbVSIAYkFFOGyaC6hYrpIHixg0c3PviHxuYzuvZehHtnmzlFhDFwvsfvkY7fbqIIgMuGG5VECHfVcI/krGWCrWbQjfePEI6cyvva+wRDBhQPtUe0UVd55Uc9jn2W4mzsEc7de2FD+pEs8kbu0WwUWANwpOJmmqeU8xbDjfPNH68djw5pqrC8XUglCQXgAPKbSDdorhm3WLh8cEMG9tfZJvXb3aILB6/TMkIQ5mTacdOw5czD5AaMFCFrRQ9zP6va1gnVL4w1E4wrOH3j4um9isl10FRQ6ULliUz5XwubwhBobJR5CDGEuVTqQtDD3XzpmgIX3attY9OayS9J1Yph4QAv/YZLR/mGnPZSRf5QHfHrZUl2I947VazJvrl77Z3e2t/q2gFBqZBlqvBrUEDUiwofZAhQ3uWe1bo6F+CjCO/0HBwkjDrLYqqv/UN1vciXLStE/K4HLq6Zh+t3NOx9BdmsXmyCPWMkzM1h6Lpgf3qSsKP+ygctlMIpqwkqoexvw7O/s0fS+FBLlQqUeNCAVrci/NXc9LpQF/3LeoRyTKLxoIB7m5klzWzXRRV/QdieH9mX2OJ4BX3E1uT+4dfkSy7fh3JImRvZ0meMNTSsHUiHoVBFvUIfnuchu6g9lYV/7Vevvy6O1yzjZIHPXYscI=
