sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

install:
- gradle buildVertx
- gradle assemble

after_success:
- export REPO=enmasseproject/topic-forwarder
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -t $REPO:$COMMIT .
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS; docker tag $REPO:$COMMIT
  $REPO:$TAG; docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER; docker push
  $REPO; sh .trigger-travis.sh; fi
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: i7IxKhBO5ZQzPCdxBqvr9lbWGC4dkUJ/vvH1YP8c0/it9Kpt09dNSyEX0momNv+H+nkOKxwfCfORItQ+fu9D4SvafbeexhXlYYmRlzWHcK33Ty/nMrP8VZcE5xa8wgKk29t1N6tSRTOyYMEx6CyA/j6awB+XwtzBTxt/p1lvy63uj+kMlBiACLGOR/DMOD0BUMEeaJOqsvtqa6MnfeqO3dl0dMQnEyaaIz+jW+zlHpIFuvWBouYAOlFXe8iZoILZM6Qv0gqJNQ7QjlkNAJ9o9vll429KAyKv/zMmPBhUp18M1VLMZ+BQlTRUNB/t4xMAAjeOPU8mKNwTkKMMKinJaJ0d6D1MWdTp7jqzmRlhOqk2TGnLlPd+K2uFzE9yzFaJgoF8+d3ypLxNM09G/lsf37R2VKXC2bQEk83qZAQ9gTnCZX06EvRTDtzeNpe+D7rQpGcLyF0G8YGMcBdKR8FFjEZnSz45+fqbpZbSnkvsbRh61AZ9GeaRmGM/YX6vZJm4N88uBufoAR/rpmFt5r3m1/k89t491P8VrxSIZSdwR523sl/zCP9Bo4u+OHjXZX1Zdoheu4aYpiF8zuqr2HoDERrRvqvf7sSdJiTJ5TgxrPEL500GHUzfxUofS39tqjCgvwTZjkl/movHLWRflqbcO7dedGIk0qzJS+n84YUGHs4=
  - secure: iGlHW2SmiPJAkh9Sror7M4KxtyQC78vTvJJz8e9T9js1+FwpGUHaiStKQPfkY4NGRegaPt6jX89xahV4U85ooDTfauOL+U3YUYMFfJzFM4768JVQOI7z9xyKJPpA37TAgFpGx3bRUye/DD0WsNhedjyFhHrsFhfOYRxwL7T5jTu/tDGe/h57fx714qkQMe+tOCkOKEbDLoOqFdAkF0ExuL34BXh/Eq4KB6GH6/7vOgFftnGU/ih3BC+uHBJKmbB6hRHgXY/fMv3eyrefzXvuM09N6eLKFss3di2BXX3aPC4y2mCTPb2ngAo/Ohowfuy2e0zdYxiFtLGy91o6qQTfjkizn1QASbarzkvxEpuelFd2jb48VHNKPl79fYCMne+LsGYt2yOQJIhY+8Fh7xgK2FgLCCBqnutWE57YjuunuDLTlqkheiHWCHY5cCRLikheU5EFNkzAPotUzjlQG6+0+Q56fXHjdPWZ58q6FZGaQx3BcO2oOFPC0Vear4p5N33Ftg5pudGQHtm8fnII5RYJQx8EQ0L/AypLxiAVKTjX5uvNFROLJ8KledybkyEgxD1qzBaY4uLDIWkkUF4MB+uACJ2HugeVRoJ/IdaScM+8cCeB8mKrkIS8sIgQZPwWoOOG7riGwvHia50kN34sdElSiWXVKQpflXb9bbbw5zsdRO8=
  - secure: l4uyAgkeL7R3veZjreBByAtgpqpdvSiGsOWcDT7UE7uWECSMuVU9Xcxo38FbN6TcyxTqCLw0Rs/ux771A8bEw3vNE+0aXhFET1ERVfnmbftRxX4WCs4vsgSo89WpED9tuhpfufAt4ZCvJK5DyCjka5oNBmkGmB1KG9+Es6sTpHU3HQ3SPUjELI/liPv3Pnx7zJuIQq778otM3ztyNzWwYGHFj8iybtBkEqZCw3+iTdRChEdmTMcqBr7DuAMYK0gDGZ0zwOmB0m9Jk4ubZa92hOhrVTBwcuMfJ6dFx6TvDlilnsG8ZvkXcYCnus5Yw0F4/4tqGcy4fb7Sq4y8Exub0MjQzUjI96crY+a+HGNYojaMJx5ccTV8M3YsfljPXIghf/nX+Er7RSe5wAUTh6M+WLeXqX+/ur78xueebh18oC2rR4VH9oUv+j4uA2Wl5yZWlLpWYgK31FBYEuKsdCgHtfAsRbpwvU+7MHnNzrcWaJGuANUvmbpucDW2mKf+n1GzkqN1bg68E/57UgAiA8gu58X4i3Q8ZFujwjwahaQ+cg/COXN7j6249eNQW9YvqC0Ey8kFY2bDMb6vMLav+0aFxZMLZAgoXfsR4rYs4w5tmzRbvzuJSug0hDZOIcVOZxiDc6UaJjzhUZzK40CoIc9fAkvzBfoANRYhzz+lOtsRhMw=
  - secure: CY5RfrL10eNA6j3FwI1xwfoccnnponSltxKJCA/Mk11/lR7KsA4SvakR3dzysVE4kK4hZl2EDYmk2Z8Nazq6Fa0cadVZ9zFeghnm3HFJjfjW7Mi77tjlxeJH77q8YcS61YDnG7iuuvtglXOQTA1sIG68cK/xGIrarvHbj6ZKMEdrYog/HP06eYsXlPEW5RtL+e8YQTSo2j1lDYX5joblJzneHaXKe5YdOE0IWplETb7RJNa107MnX0OlCN7+wRoXHhocC7Gow/ZGTmUCDl8YTQ6QnpHS4X/0dDybQfJBZ1CdAoOYYMWSRNg99HwsEAN8ITImA9GpsIl9T8YBUci27djJ0G+VE0PWdBVLm32lzK/Sq4EDSlt/Ds8DREacYIBjyzEC0dRRD9K5YlWrT4ulFvf2jDiOY5iZkqN4yt1HqRjpLUCKOueVnbAyw5/fwJHIQQnSdeAP8kbm03LKUosKMYfJTaWdGKkOz9kw7jPAt0W9txD+i8u1a7vgnM6yk19KwfdlzHguNEoV0p/xOXI1sjqz/s8aB7Vl/Pv8mHwyCLwbpXN8e9DKzh2+A7y2Froz80pDTQ/kwyBNa1lvWh0ltS9F/NWQF1fkhJeYDPMYqC2yEsRfn/talCIqPVdEfmIuHUkfF6C73YreDGz+j7rZ4nmj2L/Bo8fQpkdU+lGXjks=
