language: ruby
notifications:
  email: false
rvm:
- 2.2
script:
- make
after_success:
- curl -s https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master/trigger-travis.sh
  | bash /dev/stdin
env:
  global:
    secure: kFg3lbeFcrSrmipsVFBUuJHGSIN3zstMJ0Pasfa+qjuTN63uJS5h9o7hQDZtmhNUbdvuCnyMozvLMZUNs6qjalv4viR4f3whtFOF1DKYIqbi6IGtvLEkTgrBVd2ZM3MC9gITf03GRN1k2DCq3svhmA9EM5D75WjuMk3u5gt7rSWYClH0814ji0W8C4mX0N6yG1YziwWcupEV45w6DY80nEzSSUr73NOSCt3l3t8uoBd3eJIect/9OkwhB675KraOQCweOnmJ8EPv/QLh8B4/TgicApPXU3EnPvRsiH6bvRVH5z+LGRHGq/ujMqsWM1Jxcdzcbi6DUOsY6nJIIow1+Vb7yPWrCz8xHUpJFAQMR/xvLLIrAE9yiQAgOzV/cH2Me219gLJxy/OaeHGFinFxY6BMDC3YfiX2KkTDyaSRV19aM6l+XRhJUpZUPOURigT5PK7JZ89uHdUGD5zRacRvm6nWLMwbbMHr4yzleUbXo1G/Qlh58E+Nq4eC0vxuyDQybT1EWxUeUp7l9bYmq3/VFVo0dZg7lQgaisJa+tpDPch66t/yR2ijhgZBG4+X7Aikh0zc4ZG3UOZXQQuYiylBGddlA/1x/I0L5k4WLRPDRD2Y9U0PNLIfCnzJVcbcvl/YjMsX/bqHcNfHsITxKkP248uGW+JTZ5XNdk39YwHa5DE=
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HepZcALZznJ9XL1gumw4EqtG2doiWX+dEdUy0Qug+DcFM6mTb7m61YIrYmiw0h2FCqzozsSjlDjKfBLUgnUalj6f6LZCQKqThh04VKQoBmDJbUoOX7nSiaGeV9SJ18zeG8MrIkoHriJVGnfKUTL870RSQGzRvCXOUyQdx9gy/kfFFM4R9eUN8XOH/nMdmMhtoqwlhfjcY8T0qeKlCISqFCXlan+uIV7KERVSiiBdK4L4fsA5VB8Dd3SUHKe2zpcntowsBXfGI9wemWe++FysZ4Wsg+bBohiZ11A2xeHWCpswosvUHl8OcRyQDK5RqLsphdhTcFxaKvuyXl8v0eecg4ktdHkVQ0EbEauTtd/19lDa4oNpv/Thm3ElKpM77xq4gf0CLW/QNCO6OSQ9zPKughyaH3b/lseLWvVxYEKsPanRdYCZO0PjVOUGtbUpPRxP5CkNDEkW7mpfbK0IgxAemGy0mcTnSWFKQOgdB9iyiZA+lrHdrF9pc1rj5QPbDE8e7mn7FoosPsZuwGjZAb/7lBdZ4aerUXHHsBoyRrVEMvj1qABv9UJtokgo3rBoY/JGdHX9Rq9gsVVQeLLFir5EIFlsTXoaj4z+NvwC5ODklNdBoQvkXYzZ6z9OYsCGDjl09rFi7AbMXCM7nLeKzUv3XQbuEr9iHHpkWhKO8gc8hNw=
  file:
    - generated/enmasse-template.yaml
    - generated/tls-enmasse-template.yaml
  on:
    tags: true
    repo: EnMasseProject/enmasse
