sudo: required

language: java
jdk:
  - oraclejdk8
notifications:
  email: false

services:
  - docker

before_install:
  - docker pull ppatierno/qdrouterd:0.7.0-repo
  - docker run -d --name qdrouterd -p 5672:5672 -p 5673:5673 -v $TRAVIS_BUILD_DIR/src/test/resources:/conf ppatierno/qdrouterd:0.7.0-repo qdrouterd --conf /conf/qdrouterd.conf
