sudo: required
language: java
jdk:
  - oraclejdk8

services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

script:
    - docker run -d --name "origin" --privileged --pid=host --net=host -v /:/rootfs:ro -v /var/run:/var/run:rw -v /sys:/sys -v /var/lib/docker:/var/lib/docker:rw -v /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes openshift/origin start
    - wget https://github.com/openshift/origin/releases/download/v1.3.0-alpha.1/openshift-origin-client-tools-v1.3.0-alpha.1-6e83535-linux-64bit.tar.gz -O oclient.tar.gz
    - tar xzvf oclient.tar.gz
    - cp openshift-origin-client-tools-v1.3.0-alpha.1-6e83535-linux-64bit/oc .
    - ./oc login -u test -p test https://localhost:8443
    - export OPENSHIFT_PASSWORD=`./oc config view -o jsonpath='{.users[?(@.name == "test/localhost:8443")].user.token}'`
    - gradle build
    - sleep 10
    - OPENSHIFT_USER=test OPENSHIFT_TOKEN=$OPENSHIFT_PASSWORD OPENSHIFT_URL=https://localhost:8443 gradle run
