sudo: required
language: java
notifications:
  email: false
jdk:
- oraclejdk8
services:
- docker
script:
- make
- curl -s https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master/generate-bintray-descriptor.sh
  | bash /dev/stdin router-image qpid-dispatch-image.tar.gz router-collector.py > .bintray.json
after_success:
- curl -s https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master/trigger-travis.sh
  | bash /dev/stdin dockerfiles
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: Tmtr8DO19O/e2wKXjRWBuFUtJAk1FaNUh7pKPDal+Iw/DPrl0tMgOJnVUyjNDyRPGUHWeRpczdTphwMgm54+W3BJb8isQSAI2d5KWsDoYZyFJva2F1vLY3ZMRxz8Br4TH6l101/EXIVdF/lZusx7mT3vmIKon/ZXJcm+PHZvyAasmeVzfmGhLVWRBJzH3WVDWRFZFpRRZF7/zI5AqqRDi7ulO8VTPp2SQWolFBoM9qw1lYX+HtGtEUWyJOpYblDAanyNDRZwabu36/q/wjx682EJ7vm4SBYhcQwNLMWzFq37Sp5GekoIyf5C+vuMODOFYDjF0qnO/LDo/9amZiISsoa14ctf7T3JpdHX3KwNrhhQ3PyRBgMDUUS2rSTVZ/LueO0oB4b2tPDJyaz03oeVOUMsG9/sw1Dy7/zZQVfjN80x+OqfxrRUkpLYRiXRkd8syytDBZzk4qzlgAF8jka4AYcJMhbemeZA5dD8aMHSlUUwA6QC8lNXdS+22Vd29Q6p3NGr2xQT/ZA+HIQirmX9oUTDxOGcCqdCBoSUwDusdSCxhEiwuy2rv7Rp/kQmh2Nhs07/XuvGpAFL6CTlOmz+WhFHectA1v50hOF8z8jnqfP1WEw3KUrq1CRca2mnQIijJLi6emoZaGBbmQ65eSUuuzF9a3KTAWcgNKD9aoWFWyE=
  - secure: FOYeixraWuO7TjPEGfMbXN9ZNR5d1VDEKags9lFaWM1f16kNB+RqEQgB6js6/FFuVDIyuqCXfeRMl+rvH/7ZaIwUb7mybmLCqjNaZclVCFla/uAFoav8HSRa4gpT2x0G1MZY6d9aIKrNR32PDwhtgRpMFnHJEFxFlcqnX7Lb8bLKZDKe3if1K9hg8y14cpZjOqxHpwIDIrBT0SMW5hTwkn4r4Ita340ELCdWeLjW5CMrQQVOWpqFWcIo3VI+z0PI4xnYmcgx0sOLnWCiokRrMgX6nDmluAof/MbALo2iF49x4TSZI3S/ZJErxDWrYly3kPC7UGsPxdUBwzZdtltkNsB7mcnbWtQdgNuZ2aoZ2q6vDkk72x0xHWVkVRgG49Lg9gOEVLhduUQS+9oKR68PlkZq6IM4SNK5CIB7EWd03RCHx7dt6lKCHO0cFffRM2YSzvd4cOE3icVZop+4HDZZHpbMl7BAAdjhZJvz3RtCG7W6mGRprM2ZDxDJEescVgs12mTibLcxd0fqMMmNZOrF7C22lL0CWf/eCY9yBFuaEPAFEOSlynHltKHK6UeoRRLSR+xxebK769kAwRQofggqTmIqXS6OEOE+w/jphQpacBmu9CxiRjDegwjztN1zsraieklP/CDLpcj3UByqSw5KGKUV3AP1sD2EdU1F+vJruEM=
deploy:
  - provider: bintray
    file: ".bintray.json"
    user: "${BINTRAY_API_USER}"
    on:
      tags: true
    key:
      secure: bubHP4ykH0niJnMpwPJp9SeFgFBL3q2Ff5r4EAW223nc+F/Iv/Ne389uvvJDmBwLx7gfoJI9/m7Yw3szG/TOYtYAILaoneezx7NJwV3OCVbSQw/M6snzbPBA4l1SZAVJ8auMhQiHkhenKKGAFblyWrY+jfWOdM4tlwvLyCWRWFX8AnFdWHZSSNJpMe162T8bS95K9b1t9xvquMPTnYXwYTx44+YdNCGx4CH9amhBvB0dzFc5zlE3c58PidtM6m2yinLcaFOKo4z9LpSAasV11fo8+/I4TXMjiNXEUKDU1MuEb7sWE6j9oJdObiQiR4pGEd/IzQgD7unMLsfRlLi/zHm6wUYH2q9rEHfIkuwwg2PsaNRBeKxUoUg4t33U+piikTIM5YHgwXhDzyDv1lJBy8qW2MZajyZPc1nwrh/dJqyXOYcQfy/rF1VeQ8D0z8MiCz/L4f4Vvifw64NE8wzc1E1vyKcaKHbP4yfypkGMqGC9PAH/ELOPkpzRIo8Igsl6v7RLfG3XrJQVSWXtOK4sk1hM5hHGCvcAtELFTpFFp5qkXb6f9R53aGNXd5254U9cdJfeOnvNJCQmKuR4O2fysUKAfC8Hlpwsa1R720PB6z+AXmAXJDlszAq+m0OxDZntLlEyTgsSYQZ0Ob55dOxHLNac+aLsrqe1V9UoFjmMyvM=
  - provider: bintray
    file: ".bintray.json"
    user: "${BINTRAY_API_USER}"
    key:
      secure: bubHP4ykH0niJnMpwPJp9SeFgFBL3q2Ff5r4EAW223nc+F/Iv/Ne389uvvJDmBwLx7gfoJI9/m7Yw3szG/TOYtYAILaoneezx7NJwV3OCVbSQw/M6snzbPBA4l1SZAVJ8auMhQiHkhenKKGAFblyWrY+jfWOdM4tlwvLyCWRWFX8AnFdWHZSSNJpMe162T8bS95K9b1t9xvquMPTnYXwYTx44+YdNCGx4CH9amhBvB0dzFc5zlE3c58PidtM6m2yinLcaFOKo4z9LpSAasV11fo8+/I4TXMjiNXEUKDU1MuEb7sWE6j9oJdObiQiR4pGEd/IzQgD7unMLsfRlLi/zHm6wUYH2q9rEHfIkuwwg2PsaNRBeKxUoUg4t33U+piikTIM5YHgwXhDzyDv1lJBy8qW2MZajyZPc1nwrh/dJqyXOYcQfy/rF1VeQ8D0z8MiCz/L4f4Vvifw64NE8wzc1E1vyKcaKHbP4yfypkGMqGC9PAH/ELOPkpzRIo8Igsl6v7RLfG3XrJQVSWXtOK4sk1hM5hHGCvcAtELFTpFFp5qkXb6f9R53aGNXd5254U9cdJfeOnvNJCQmKuR4O2fysUKAfC8Hlpwsa1R720PB6z+AXmAXJDlszAq+m0OxDZntLlEyTgsSYQZ0Ob55dOxHLNac+aLsrqe1V9UoFjmMyvM=
