apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-k8s-rules
spec:
  groups:
  - name: ComponentHealth
    rules:
    - alert: Component_Health
      annotations:
        description: '{{ $labels.summary }}'
        value: "{{ $value }}"
        severity: warning
      expr: health == 1
      for: 180s
    - alert: Component_Health
      annotations:
        description: '{{ $labels.summary }}'
        value: "{{ $value }}"
        severity: critical
      expr: health == 2
      for: 180s
    - alert: Component_Health
      annotations:
        description: '{{ $labels.summary }}'
        value: "{{ $value }}"
        severity: unknown
      expr: health == 3
      for: 180s
    - alert: Component_Ping
      annotations:
        description: "Component unreachable"
        value: "{{ $value }}"
        severity: critical
      expr: up != 1
      for: 180s
    - alert: Address_Space_Health
      annotations:
        description: '{{ $labels.summary }}'
        value: "{{ $value }}"
        severity: warning
      expr: address_spaces_not_ready_total > 0
      for: 300s
    - alert: Address_Health
      annotations:
        description: '{{ $labels.summary }}'
        value: "{{ $value }}"
        severity: warning
      expr: addresses_not_ready_total > 0
      for: 300s
    - alert: Terminating_Pods
      annotations:
        description: '{{ $labels.pod }}'
        value: "{{ $value }}"
        severity: warning
      expr: kube_pod_container_status_terminated == 1
      for: 180s
    - alert: Restarting_Pods
      annotations:
        description: '{{ $labels.pod }}'
        value: "{{ $value }}"
        severity: warning
      expr: rate(kube_pod_container_status_restarts_total[10m]) * 600 > 5
      for: 180s
    - alert: Pending_Pods
      annotations:
        description: '{{ $labels.pod }}'
        phase: '{{ $labels.phase }}'
        value: "{{ $value }}"
        severity: warning
      expr: kube_pod_status_phase{phase="Pending"} == 1
      for: 180s