---
# tasks file for clients installation and compilation
- name: CLIENTS | delete old clients executables
  file:
    path: "{{ client_executable_folder }}"
    state: absent

- name: CLIENTS | create client_executable folder
  file:
    path: "{{ client_executable_folder }}"
    state: directory

- name: CLIENTS | Install cli-rhea client globally
  npm:
    name: cli-rhea
    global: yes

- name: CLIENTS | Install cli-proton-python client globally
  pip:
    name: cli-proton-python

- name: CLIENTS | download cli-qpid-jms
  get_url:
    url: "{{ cli_qpid_jms_url }}"
    dest: "{{ client_executable_folder }}/cli-qpid-jms.jar"

- name: CLIENTS | download cli-artemis-jms
  get_url:
    url: "{{ cli_artemis_url }}"
    dest: "{{ client_executable_folder }}/cli-artemis-jms.jar"

- name: CLIENTS | download cli-activemq
  get_url:
    url: "{{ cli_activemq_url }}"
    dest: "{{ client_executable_folder }}/cli-activemq.jar"

- name: CLIENTS | Clone rhea repo
  git:
    repo: 'https://github.com/amqp/rhea.git'
    dest: "{{ rhea_path }}"
    update: yes
    clone: yes
    force: yes

- name: CLIENTS | Install rhea npm dependency modules
  shell: 'npm install'
  args:
    chdir: "{{ rhea_path }}"

- name: CLIENTS | create rhea.js using browserify
  shell: 'npm run-script browserify'
  args:
    chdir: "{{ rhea_path }}"
