apiVersion: v1
kind: ReplicationController
metadata:
  name: configmap-bridge
  labels:
    name: configmap-bridge
spec:
  replicas: 1
  selector:
    name: configmap-bridge
  template:
    metadata:
      labels:
        name: configmap-bridge
    spec:
      containers:
      - name: bridge
        image: enmasseproject/configmap-bridge:latest
        ports:
        - containerPort: 5672
