sudo: required
language: java
notifications:
  email: false
env:
  global:
  - SCRIPTS=https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: GK/V6Z51R/ABbttiiLgmQkWMn5edazCEc65zAF7h37WausP2koAFLjRsxhmLK/Y3VIivS2Lehgfna5iFwoXNMnfrjr/zWVImiV6Ew7XIczE8sc7qzpBXO6/1xDjbQwJ5hj+J/vPRdpqK6ss+Bnjstn2gPXtj+DCl4Md/cfM9kN1U79kUVm8/jG73yZ19mPybdixAesD49/Q9tguWsI3DagZcFiF/QtVNdv85Y1VWCHsDgBpl4aXk2VtaxKf/wQZF2UuKCUetdtlFbIMJFUTXgiHHI5C/HiDwm0DUN/EhywO7hAME+Rwef/fhoLhebupQ6fn+476VKSKgMlxA60pbkrk3AF7wEEGi/iXoLggbQ6Jx/vYihW/FN0D1KY6z/k1wZfm57l9nMsvUq8pWdzDMpLXd2gPfO5qTzAwKxNTEMJEb1LhtEKkO5zDIUnHy2UV2ZO5UI8jEglcxiMiTGd+W70UApJAgRB0LPYwcB6s3EzOhSD7vm11KS2ZrFz5s3xoGpzEDx4MuAe+/RHaaB3MKaGjqZZfBZdQoCG6lJ9xxioHU0WX09xWWB51HNHdU24kMozyoFWJ9LeheU+NBvFCTL0TikW4S4mFT2zLOMINn4dWSRe1ZAreUJH1qWhol5fELYXC6/mSdllbPTy9ge1yXnqxqAQnJ24NV9mRMk0gXsF8=
  - secure: P3QtsDO807TOIhGIEP8cctvP+fp1T7EPPS9ihCqRrr0Z+V5AqHgSbHJUAI4k0+a1LO++INWM4dgw67wvYutPt7kx8uuewVYzgW91dxyVag5P981TRHtI4lNQTlY6s+l/j2g1MnV0/Yi9VNU7CvXDWiveUTw6y0dqfRFwe5/K0+Gbaj4McrM8lToWD2X73pjA9hPFw4Vse0CVUqJmeyf3Cv9wUHQmdZqinumrmie733La3pUFAkAvxhGEOWZPCW4ivclHrKLj8NnKGQVHtyc1igUHueqviQRHW9DGIyZiaU7Bs6SyesTVfr0WAS+AC5h+FhISbt0+zHa2mAH/BA/Wk14bghscMFqXOZD6Wdzw948kKQ+tV0BjYcvpeCAyA4UATtlW4D9HYBo3sTtXa2flP77QkBBoVTzaIWXE/6je7tfLu00ehFnmbHlkXcx9aCW8ULJKbrjpPa9uKiWCSPVUqGE0BuPkHLYnWH1FnGfFQqJO4zA/5WokEoWNH3DWqtGP6Tes0bNLXj0wrueOoOXAbLzev5XWOTQL6Rqb1o2bxetht3A9wx0HPY1I4rh+bU03KIwHs9DwtOzY/rDqQqItWJ36xTuTJdm2G1jFHNQ5wUCBFGpVShP0mh1yDItEqssUaKtrdhy1Obwjhm32cqosjehsbip8g7ceNoJPnzMeP+M=
jdk:
- oraclejdk8
services:
- docker
before_script:
- curl -s ${SCRIPTS}/setup-tests.sh | bash /dev/stdin
script:
- curl -s ${SCRIPTS}/docker-build.sh | bash /dev/stdin enmasseproject/qdrouterd .
- curl -s ${SCRIPTS}/run-tests.sh | bash /dev/stdin ${COMMIT} "" enmasseproject/qdrouterd
after_success:
- curl -s ${SCRIPTS}/docker-push.sh | bash /dev/stdin enmasseproject/qdrouterd
