kind: Route
apiVersion: v1
metadata:
  name: device-registry
  labels:
    app: iot-registry
    compnent: iot-device-registry
    enmasse-component: iot
spec:
  port:
    targetPort: https
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: iot-device-registry
