apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "keycloak-controller"
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: enmasse.io:keycloak-controller
subjects:
- kind: ServiceAccount
  name: keycloak-controller
  namespace: ${NAMESPACE}
