apiVersion: v1
kind: Service
metadata:
  labels:
    application: enmasse
  name: iot-interior-interconnect
spec:
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: http
    port: 8080
    targetPort: 8080
  - name: inter-router
    port: 55672
    targetPort: 55672
  selector:
    application: enmasse