apiVersion: v1
kind: Pod
metadata:
  name: messaging-clients
spec:
  containers:
  - name: messaging-clients
    image: docker.io/kornysd/docker-clients:latest
    ports:
    - containerPort: 4242
    livenessProbe:
      tcpSocket:
        port: 4242
      initialDelaySeconds: 10
      periodSeconds: 5
