kind: BuildConfig
apiVersion: v1
metadata:
  name: fabric8-s2i-java-custom-java8
  labels:
    app: enmasse
    enmasse-component: iot
spec:
  triggers: 
    - type: ImageChange
    - type: ConfigChange
  source: 
    type: Git
    git:
      uri: https://github.com/enmasseproject/enmasse
      ref: master
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: fabric8-s2i-java:3.0-java8
      dockerfilePath: iot/fabric8-s2i-java-custom/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: fabric8-s2i-java-custom:java8
