---
apiVersion: v1
kind: Template
metadata:
  name: console
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: console
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: console
    - port: 8088
      protocol: TCP
      targetPort: 8088
      name: ws-proxy
    selector:
      name: console
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: console
    name: console
  spec:
    containers:
    - name: console
      image: gordons/dispatch-console:v1
      ports:
      - containerPort: 8080
    - name: wsproxy
      image: gordons/ws-proxy:v1
      ports:
      - containerPort: 8088
