---
apiVersion: v1
kind: Template
metadata:
  labels:
    app: enmasse
  name: tls-queue-inmemory
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      address_config: address-config-${TENANT}-${NAME}
      app: enmasse
      group_id: "${NAME}"
      tenant: "${TENANT}"
    name: "${TENANT}-${NAME}"
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: enmasse
          group_id: "${NAME}"
          role: broker
          tenant: "${TENANT}"
      spec:
        containers:
        - env:
          - name: QUEUE_NAME
            value: "${ADDRESS}"
          - name: GROUP_ID
            value: "${NAME}"
          image: "${BROKER_REPO}:latest"
          lifecycle:
            preStop:
              exec:
                command:
                - "/opt/artemis-shutdown-hook/bin/artemis-shutdown-hook"
          livenessProbe:
            tcpSocket:
              port: amqp
          name: broker
          ports:
          - containerPort: 5673
            name: amqp
          - containerPort: 61616
            name: core
          volumeMounts:
          - mountPath: "/var/run/artemis"
            name: vol-${TENANT}-${NAME}
        volumes:
        - emptyDir: {}
          name: vol-${TENANT}-${NAME}
        - name: ssl-certs
          secret:
            secretName: qdrouterd-certs
- apiVersion: v1
  data:
    "${ADDRESS}": '{"store_and_forward": true, "multicast": false}'
  kind: ConfigMap
  metadata:
    labels:
      app: enmasse
      group_id: "${NAME}"
      tenant: "${TENANT}"
      type: address-config
    name: address-config-${TENANT}-${NAME}
parameters:
- description: Storage capacity required for volume claims
  name: STORAGE_CAPACITY
  value: 2Gi
- description: The docker image to use for the message broker
  name: BROKER_REPO
  value: enmasseproject/artemis
- description: The default image to use as topic forwarder
  name: TOPIC_FORWARDER_REPO
  value: enmasseproject/topic-forwarder
- description: The image to use for the router
  name: ROUTER_REPO
  value: enmasseproject/qdrouterd
- description: The link capacity setting for router
  name: ROUTER_LINK_CAPACITY
  value: '50'
- description: A valid tenant name for the instance
  name: TENANT
  required: true
- description: A valid name for the instance
  name: NAME
  required: true
- description: The address to use for the queue
  name: ADDRESS
  required: true
