---
- name: Deploy Prometheus
  shell: oc apply -n {{ namespace }} -f {{ playbook_dir }}/install/prometheus

- name: Base64 encode Alertmanager config
  register: config
  shell: cat {{ playbook_dir }}/install/alertmanager/010-Config-alertmanager | base64 -w0

- name: Create Alertmanager config secret
  lineinfile:
    dest: "{{ playbook_dir }}/install/alertmanager/020-Secret-alertmanager.yaml"
    regexp: '^  alertmanager.yaml.'
    line: '  alertmanager.yaml: {{ config.stdout }}'
    backrefs: yes

- name: Deploy Alertmanager
  shell: oc apply -n {{ namespace }} -f {{ playbook_dir }}/install/alertmanager


- name: Deploy Kube-state-metrics
  shell: oc apply -n {{ namespace }} -f {{ playbook_dir }}/install/kube-state-metrics