apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: enmasse
  name: nginx-config
data:
  nginx.conf: |
    http {
      server {
        listen 8080;

        location /prometheus {
          auth_basic           "Prometheus";
          auth_basic_user_file /usr/local/etc/htpasswd;

          proxy_pass           http://prometheus:9090/;
        }

        location /prometheus/ {
          auth_basic           "Prometheus";
          auth_basic_user_file /usr/local/etc/htpasswd;

          proxy_pass           http://prometheus:9090/;
        }

        location = /alertmanager {
          auth_basic           "Alertmanager";
          auth_basic_user_file /usr/local/etc/htpasswd;

          proxy_pass           http://alertmanager:9093/;
        }

        location /alertmanager/ {
          auth_basic           "Alertmanager";
          auth_basic_user_file /usr/local/etc/htpasswd;

          proxy_pass           http://alertmanager:9093/;
        }
      }
    }
    events {}