apiVersion: admin.enmasse.io/v1beta1
kind: AuthenticationService
metadata:
  name: standard-authservice
spec:
  type: standard
  standard:
    storage:
      claimName: standard-authservice
      deleteClaim: true
      size: 1G
      type: persistent-claim
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 512Mi

