kind: Deployment
apiVersion: apps/v1
metadata:
  name: iot-gc
  labels:
    app: iot-core
    name: iot-gc
    enmasse-component: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-core
      name: iot-gc
  template:
    metadata:
      labels:
        app: iot-core
        name: iot-gc
        enmasse-component: iot
    spec:
      containers:
      - name: collector
        image: ${IOT_GC_IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        resources:
          limits:
            memory: 128Mi
