apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: enmasse
  name: enmasse.io:address-space-controller
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "list", "get", "create" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "rolebindings" ]
    verbs: [ "list", "get", "create" ]
