---
namespace: enmasse
multitenant: true
enable_rbac: true
keycloak_admin_user: admin
service_catalog: false
register_api_server: false
standard_authservice_resources: standard_authservice_keycloak
secure_api_server: false
api_server: true
authentication_services:
  - none
