- name: Check if keycloak route exists
  shell: oc get route keycloak -n {{ namespace }} -o yaml -o jsonpath={.spec.host}
  register: keycloak_route
  ignore_errors: True
- set_fact:
    keycloak_http_url: "https://{{ keycloak_route.stdout }}/auth"
  when: (keycloak_http_url is not defined) and (not (keycloak_route.stdout | search("127.0.0.1")))
- name: Retrieve service cluster ip
  when: config_exists.failed and (keycloak_http_url is not defined)
  shell: oc get service -n {{ namespace }} standard-authservice -o jsonpath={.spec.clusterIP}
  register: authservice_clusterip
- set_fact:
    keycloak_http_url: "https://{{ authservice_clusterip.stdout }}:8443/auth"
  when: config_exists.failed and (keycloak_http_url is not defined)
