apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enmasse.io:address-space-controller
  labels:
    app: enmasse
rules:
  - apiGroups: [ "", "user.openshift.io" ]
    resources: [ "users" ]
    verbs: [ "get" ]
