apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: enmasse
  name: enmasse.io:address-space-controller
rules:
  - apiGroups: [ "admin.enmasse.io" ]
    resources: [ "addressplans", "addressspaceplans", "brokeredinfraconfigs", "standardinfraconfigs" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "services" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch" ]
  - apiGroups: [ "route.openshift.io" ]
    resources: [ "routes" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "statefulsets", "deployments" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch" ]
