apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enmasse.io:tenant-edit
  labels:
    app: enmasse
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups: [ "enmasse.io" ]
    resources: [ "messagingaddresses", "messagingprojects", "messagingendpoints" ]
    verbs: [ "create", "get", "update", "delete", "list", "watch", "patch" ]
  - apiGroups: [ "iot.enmasse.io" ]
    resources: [ "iotprojects" ]
    verbs: [ "create", "get", "update", "delete", "list", "watch", "patch" ]
