apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enmasse.io:tenant-view
  labels:
    app: enmasse
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups: [ "enmasse.io" ]
    resources: [ "messagingaddresses", "messagingprojects", "messagingendpoints" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "iot.enmasse.io" ]
    resources: [ "iotprojects" ]
    verbs: [ "get", "list", "watch" ]
