apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ${CATALOG_SOURCE_NAME}
  namespace: ${OPERATOR_NAMESPACE}
  labels:
    app: enmasse
spec:
  displayName: EnMasse Operator Source
  image: ${REGISTRY_IMAGE}
  publisher: enmasse
  sourceType: grpc
