apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: enmasse-sub
  namespace: ${OPERATOR_NAMESPACE}
  labels:
    app: enmasse
spec:
  name: ${OPERATOR_NAME}
  source: ${CATALOG_SOURCE_NAME}
  sourceNamespace: ${CATALOG_NAMESPACE}
  startingCSV: ${CSV}
  channel: ${OPERATOR_CHANNEL}
  installPlanApproval: Automatic
