---
apiVersion: v1
kind: Template
metadata:
  labels:
    app: enmasse
  name: direct
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: address-config-${NAME}
    labels:
      app: enmasse
      type: address-config
      group_id: "${NAME}"
  data:
    "${ADDRESS}": '{"store_and_forward":false, "multicast": ${MULTICAST}}'
parameters:
- name: NAME
  description: A valid name for the instance
  required: true
- name: ADDRESS
  description: The address to use for the address
  required: true
- name: MULTICAST
  description: If the address should have multicast semantics or not
  required: true
