---
- name: Create EnMasse Service Broker Deployment
  shell: oc apply -n {{ namespace }} -f "{{ playbook_dir }}/resources/service-broker/deployment.yaml"
- name: Create EnMasse Service Broker Service
  shell: oc apply -n {{ namespace }} -f "{{ playbook_dir }}/resources/service-broker/service.yaml"
- name: Create the service broker console route
  shell: oc apply -n {{ namespace }} -f "{{ playbook_dir }}/resources/service-broker/route.yaml"
- shell: oc extract secret/standard-authservice-cert -n {{ namespace }} --keys=tls.crt --to=-
  register: secret_result
  when: (keycloak_ca_cert is not defined)
- set_fact:
    keycloak_ca_cert: "{{ secret_result.stdout }}"
  when: (keycloak_ca_cert is not defined)
- name: Create service-broker-secret for secure info
  register: broker_secret_exists
  failed_when: broker_secret_exists.stderr != '' and 'already exists' not in broker_secret_exists.stderr
  shell:
    cmd: |
      cat <<EOF | oc create -n {{ namespace }} -f -
      apiVersion: v1
      kind: Secret
      metadata:
        name: service-broker-secret
      type: Opaque
      data:
        keycloak.username: "{{ keycloak_admin_user | b64encode }}"
        keycloak.password: "{{ keycloak_admin_password | b64encode }}"
        keycloakCa.crt: "{{ keycloak_ca_cert | b64encode }}"
      EOF

- name: Keycloak http setting
  include_role:
    name: standard_authservice_url

- name: Check if console route exists
  shell: oc get route console -n {{ namespace }} -o yaml -o jsonpath={.spec.host}
  register: console_route
  failed_when: console_route.stderr != '' and 'NotFound' in console_route.stderr
- set_fact:
    osb_console_prefix: "https://{{ console_route.stdout }}/console"
  when: (osb_console_prefix is not defined) and (not (console_route.stdout | search("127.0.0.1")))
- name: Retrieve service broker cluster ip
  when: (osb_console_prefix is not defined)
  shell: oc get service -n {{ namespace }} service-broker -o jsonpath={.spec.clusterIP}
  register: osbservice_clusterip
- set_fact:
    osb_console_prefix: "https://{{ osbservice_clusterip.stdout }}:8443/console"
  when: (osb_console_prefix is not defined)

- name: Create service-broker-config for configuration data
  shell: oc create configmap service-broker-config -n {{ namespace }} --from-literal=keycloakUrl={{ keycloak_http_url }} --from-literal=enableRbac={{ enable_rbac }} --from-literal=consolePrefix={{ osb_console_prefix }}
  register: config_exists
  failed_when: config_exists.stderr != '' and 'already exists' not in config_exists.stderr

- shell: oc sa get-token -n {{ namespace }} enmasse-admin
  register: token_result
- set_fact:
    enmasse_admin_token: "{{ token_result.stdout }}"
- name: Create secret for catalog credentials
  shell: oc create secret generic -n {{ namespace }} service-catalog-credentials --from-literal=token={{ enmasse_admin_token }}
  register: catalog_secret_exists
  failed_when: catalog_secret_exists.stderr != '' and 'already exists' not in catalog_secret_exists.stderr