---
# tasks file for install dependencies for systemtests

######################################################
# Prepare
- name: Dependencies | Prepare enmasse tmp folder
  file:
    path: "{{ enmasse_tmp_dir }}"
    state: directory
  tags: always


######################################################
# Task for install OpenShift
- name: OpenShift | Prepare openshift tmp folder
  file:
    path: "{{ openshift_path }}"
    state: directory
  tags: openshift

- name: OpenShift | Download openshift-origin client
  get_url:
    force: yes
    url: "{{ openshift_client_url }}"
    dest: "{{ openshift_path }}/openshift.tar.gz"
  tags: openshift

- name: OpenShift | Extract OpenShift
  unarchive:
    src: "{{ openshift_path }}/openshift.tar.gz"
    dest: "{{ openshift_path }}"
    extra_opts: [--strip-components=1]
  tags: openshift

- name: OpenShift | Copy OpenShift client to PATH
  shell: 'cp {{ openshift_path }}/oc /usr/bin/'
  tags: openshift


######################################################
# Task for install Kubectl
- name: Kubectl | Prepare kubectl tmp folder
  file:
    path: "{{ kubectl_path }}"
    state: directory
  tags: kubectl

- name: Kubectl | Download kubectl client
  get_url:
    force: yes
    url: "{{ kubectl_url }}"
    dest: "{{ kubectl_path }}/kubectl"
  tags: kubectl

- name: Kubectl | Change perm of 'kubectl', adding "+x"
  file:
    dest: "{{ kubectl_path }}/kubectl"
    mode: "a+x"
  tags: kubectl

- name: Kubectl | Copy kubectl to PATH
  shell: 'cp {{ kubectl_path }}/kubectl /usr/bin/'
  tags: kubectl


######################################################
# Task for install Minikube
- name: Minikube | Prepare minikube tmp folder
  file:
    path: "{{ minikube_path }}"
    state: directory
  tags: minikube

- name: Minikube | Download minikube client
  get_url:
    force: yes
    url: "{{ minikube_url }}"
    dest: "{{ minikube_path }}/minikube"
  tags: minikube

- name: Minikube | Change perm of 'minikube', adding "+x"
  file:
    dest: "{{ minikube_path }}/minikube"
    mode: "a+x"
  tags: minikube

- name: Minikube | Copy minikube to PATH
  shell: 'cp {{ minikube_path }}/minikube /usr/bin/'
  tags: minikube
