apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: enmasse.operator.enmasse.io
spec:
  group: operator.enmasse.io
  names:
    kind: Enmasse
    listKind: EnmasseList
    plural: enmasses
    singular: enmasse
  scope: Namespaced
  version: v1alpha1
