kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: enmasse.io:enmasse-operator
rules:
- apiGroups:
  - operator.enmasse.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - "*"
