quarkus:
  banner:
    path: banner.txt
  log:
    console:
      format: "%z{UTC}%d{yyyy-MM-dd'T'HH:mm:ss.SSS}Z %-5p [%c{1}] %m%n"
  vertx:
    prefer-native-transport: true

enmasse:
  iot:

    auth:
      name: 'EnMasse IoT Tenant Service'
      port: 5671
      keyFormat: PEM
      trustStoreFormat: PEM

      validation:
        certPath: /etc/tls-auth-service/tls.crt

    amqp:
      bindAddress: 0.0.0.0
      keyPath: /etc/tls/tls.key
      certPath: /etc/tls/tls.crt
      keyFormat: PEM
      nativeTlsRequired: true

    http:
      insecurePortBindAddress: 0.0.0.0
      insecurePortEnabled: true
      insecurePort: 8080

    health-check:
      insecurePortBindAddress: 0.0.0.0
      insecurePortEnabled: true
      insecurePort: 8088
