kind: MessagingUser
apiVersion: user.enmasse.io/v1beta1
metadata:
  name: iot.consumer
spec:
  username: consumer
  authentication:
    type: password
    password: Zm9vYmFy # <- foobar
  authorization:
  - addresses:  [ "telemetry/myapp.iot", "telemetry/myapp.iot/*", "event/myapp.iot", "event/myapp.iot/*" ]
    operations: [ "recv" ]
  - addresses:  [ "command/myapp.iot", "command/myapp.iot/*" ]
    operations: [ "send", "recv" ]
