---
# get kubernetes logs
# ARTIFACTS_DIR
# RESOURCE
# NAMESPACE
# SUFIX

#FILE_NAME="openshift-${RESOURCE}-${NAMESPACE}${SUFIX}.log"
#    kubectl get ${RESOURCE} -n ${NAMESPACE} > "${1}/${FILE_NAME}"
#    kubectl get ${RESOURCE} -n ${NAMESPACE} -o yaml >> "${1}/${FILE_NAME}"

- set_fact:
     FILE_NAME: "openshift-{{ RESOURCE }}-{{ NAMESPACE }}{{ SUFIX }}.log"

- name: "get {{ RESOURCE }} from kubernetes"
  shell: 'kubectl get {{ RESOURCE }} -n {{ NAMESPACE }} > {{ ARTIFACTS_DIR }}/{{ FILE_NAME }}'

- name: "get {{ RESOURCE }} from kurvernetes in yaml"
  shell: 'kubectl get {{ RESOURCE }} -n {{ NAMESPACE }} -o yaml >> {{ ARTIFACTS_DIR }}/{{ FILE_NAME }}'