apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: enmasse
  name: enmasse.io:iot-operator
rules:
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "get", "list", "watch", "update", "create", "patch", "delete" ]
  - apiGroups: [ "iot.enmasse.io" ]
    resources: [ "iotconfigs" ]
    verbs: [ "get", "list", "watch" ]
