kind: Deployment
apiVersion: apps/v1
metadata:
  name: iot-operator
  labels:
    app: enmasse
    name: iot-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enmasse
      name: iot-operator
  template:
    metadata:
      labels:
        app: enmasse
        name: iot-operator
    spec:
      serviceAccountName: iot-operator
      containers:
      - name: operator
        image: ${ENMASSE_CONTROLLER_MANAGER_IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: "iot-operator"
        - name: ENMASSE_DEFAULT_PULL_POLICY
          value: "${IMAGE_PULL_POLICY}"
        - name: CONTROLLER_ENABLE_IOT_PROJECT
          value: "true"
        - name: CONTROLLER_DISABLE_ALL
          value: "true"
        resources:
          limits:
            memory: 128Mi
