apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    monitoring-key: middleware
    prometheus: k8s
    role: alert-rules
  name: enmasse
  namespace: {{ index .Params "Namespace" }}
spec:
  groups:
  - name: ComponentHealth
    rules:

    - record: enmasse_address_spaces_ready_total
      expr: sum(enmasse_address_space_status_ready) by (service,exported_namespace)
    - record: enmasse_address_spaces_not_ready_total
      expr: sum(enmasse_address_space_status_not_ready) by (service,exported_namespace)
    - record: enmasse_component_health
      expr: up{job="address-space-controller"} or on(namespace) (1- absent(up{job="address-space-controller"}))
    - record: enmasse_component_health
      expr: up{job="enmasse-operator-metrics"} or on(namespace) (1- absent(up{job="enmasse-operator-metrics"}))
    - record: enmasse_broker_address_memory_utilisation
      expr: enmasse_artemis_address_memory_usage / on (brokerprefix) group_left enmasse_address_space_broker_global_max_size * 100

    - alert: BrokerMemory
      annotations:
        description: "Broker {{ "{{" }} $labels.broker {{ "}}" }} has high memory usage"
        severity: critical
      expr: enmasse_broker_address_memory_utilisation >= 90
      for: 300s
    - alert: ComponentHealth
      annotations:
        description: "{{ "{{" }} $labels.job {{ "}}" }} has been down for over 5 minutes"
        severity: critical
      expr: enmasse_component_health == 0
      for: 300s
    - alert: AuthenticationService
      annotations:
        description: "{{ "{{" }} $labels.authservice_name {{ "}}" }} has been down for over 5 minutes"
        severity: critical
      expr: enmasse_authentication_service_ready == 0
      for: 300s
    - alert: AddressSpaceHealth
      annotations:
        description: Address Space(s) have been in a not ready state for over 5 minutes
        value: "{{ "{{" }} $value {{ "}}" }}"
        severity: warning
      expr: enmasse_address_spaces_not_ready_total > 0
      for: 300s
    - alert: AddressHealth
      annotations:
        description: Address(s) have been in a not ready state for over 5 minutes
        value: "{{ "{{" }} $value {{ "}}" }}"
        severity: warning
      expr: enmasse_addresses_not_ready_total > 0
      for: 300s
    - alert: RouterMeshConnectivityHealth
      annotations:
        description: Router mesh(s) have not been fully connected for over 5 minutes
        value: "{{ "{{" }} $value {{ "}}" }}"
        severity: warning
      expr: enmasse_router_mesh_not_connected_total > 0
      for: 300s
    - alert: RouterMeshUndeliveredHealth
      annotations:
        description: Router mesh(s) have undelivered messages for over 5 minutes
        value: "{{ "{{" }} $value {{ "}}" }}"
        severity: warning
      expr: enmasse_router_mesh_undelivered_total > 0
      for: 300s
