apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: enmasse-iot
  namespace: {{ index .Params "Namespace" }}
  labels:
    monitoring-key: middleware
    app: enmasse
spec:
  selector:
    matchLabels:
      app: enmasse
      component: iot
  endpoints:
  - port: prometheus
    path: /prometheus
    metricRelabelings:
      - sourceLabels: [__name__]
        targetLabel: __name__
        replacement: "enmasse_${1}"
  namespaceSelector:
    matchLabels:
      monitoring-key: middleware
