apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: enmasse-broker
  namespace: {{ index .Params "Namespace" }}
  labels:
    monitoring-key: middleware
    app: enmasse
spec:
  selector:
    matchLabels:
      app: enmasse
      component: broker
  endpoints:
  - port: health-tls
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    metricRelabelings:
      - sourceLabels: [__name__]
        targetLabel: __name__
        replacement: "enmasse_${1}"
      - sourceLabels: [broker]
        regex: '(.*-.*)-.*-.*'
        replacement: '$1'
        targetLabel: broker_prefix
  namespaceSelector:
    matchLabels:
      monitoring-key: middleware
