apiVersion: admin.enmasse.io/v1alpha1
kind: StandardInfraConfig
metadata:
  name: default
  labels:
    app: enmasse
spec:
  version: ${version}
  admin:
    resources:
      memory: 512Mi
  broker:
    resources:
      memory: 512Mi
      storage: 2Gi
    addressFullPolicy: FAIL
  router:
    minReplicas: 2
    resources:
      memory: 512Mi
    linkCapacity: 250
