apiVersion: admin.enmasse.io/v1beta1
kind: StandardInfraConfig
metadata:
  name: default
  labels:
    app: enmasse
spec:
  version: ${release.version}

  admin:
    resources:
      memory: 512Mi
  broker:
    resources:
      memory: 512Mi
      storage: 2Gi
    addressFullPolicy: FAIL
  router:
    minReplicas: 2
    resources:
      memory: 512Mi
    linkCapacity: 250
