- name: Check if none authservice secret exists
  shell: oc get secret -n {{ namespace }} none-authservice-cert
  register: secret_exists
  ignore_errors: True
- name: Create temp folder for none authservice certificates
  when: secret_exists.failed
  register: cert_temp
  tempfile:
    state: directory
- name: Create self signed certificate for standard authservice
  when: secret_exists.failed
  shell: openssl req -new -x509 -batch -nodes -days 11000 -out "{{ cert_temp.path }}/tls.crt" -keyout "{{ cert_temp.path }}/tls.key" -subj "/O=io.enmasse/CN=none-authservice.{{ namespace }}.svc.cluster.local"
- name: Create secret with the none authentication service certificate
  when: secret_exists.failed
  shell: oc create secret tls -n {{ namespace }} none-authservice-cert --cert="{{ cert_temp.path }}/tls.crt" --key="{{ cert_temp.path }}/tls.key"
- name: Create the none authentication service
  shell: oc process -f {{ playbook_dir }}/templates/addons/none-authservice.yaml | oc apply -n {{ namespace }} -f -
