apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: enmasse
  name: enmasse.io:enmasse-controller-manager
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps", "secrets", "pods", "services", "persistentvolumeclaims" ]
    verbs: [ "get", "list", "watch", "update", "create", "patch", "delete" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "watch", "update", "create", "patch", "delete" ]
  - apiGroups: [ "route.openshift.io" ]
    resources: [ "routes" ]
    verbs: [ "get", "list", "watch", "update", "create", "patch", "delete" ]
  - apiGroups: [ "admin.enmasse.io" ]
    resources: [ "authenticationservice" ]
    verbs: [ "get", "list", "watch", "update", "create", "patch" ]
  - apiGroups: [ "iot.enmasse.io" ]
    resources: [ "iotconfigs", "iotconfigs/finalizers" ]
    verbs: [ "get", "list", "watch", "update", "create", "patch", "delete" ]
    