kind: Deployment
apiVersion: apps/v1
metadata:
  name: enmasse-controller-manager
  labels:
    app: enmasse
    name: enmasse-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enmasse
      name: enmasse-controller-manager
  template:
    metadata:
      labels:
        app: enmasse
        name: enmasse-controller-manager
    spec:
      containers:
      - name: controller
        image: ${ENMASSE_CONTROLLER_MANAGER_IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "enmasse-controller-manager"
        resources:
          limits:
            memory: 128Mi
