kind: Deployment
apiVersion: apps/v1
metadata:
  name: enmasse-controller-manager
  labels:
    app: enmasse
    name: enmasse-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enmasse
      name: enmasse-controller-manager
  template:
    metadata:
      labels:
        app: enmasse
        name: enmasse-controller-manager
    spec:
      serviceAccountName: enmasse-controller-manager
      containers:
      - name: controller
        image: ${ENMASSE_CONTROLLER_MANAGER_IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "enmasse-controller-manager"
        - name: ENMASSE_DEFAULT_IMG_PULL_POLICY
          value: "${IMAGE_PULL_POLICY}"
        - name: ENMASSE_DEFAULT_IMG_REGISTRY
          value: "${DOCKER_REGISTRY}"
        - name: ENMASSE_DEFAULT_IMG_ORG
          value: "${DOCKER_ORG}"
        - name: ENMASSE_DEFAULT_IMG_TAG
          value: "${IMAGE_VERSION}"
        - name: ENMASSE_IMG_ENMASSEPROJECT_QDROUTERD_BASE
          value: "${QDROUTERD_BASE_IMAGE}"
        resources:
          limits:
            memory: 128Mi
