apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: enmasse-controller-manager
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: enmasse.io:enmasse-controller-manager
subjects:
- kind: ServiceAccount
  name: enmasse-controller-manager
  namespace: ${NAMESPACE}
