apiVersion: v1
kind: Service
metadata:
  labels:
    app: infinispan
  name: infinispan # align name with operator version
spec:
  ports:
  - port: 11222
    targetPort: 11222
    name: infinispan
  selector:
    name: infinispan
    app: infinispan

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: infinispan
  name: infinispan-ping
spec:
  clusterIP: None
  ports:
  - name: ping
    port: 7800
    protocol: TCP
    targetPort: 7800