apiVersion: v1
kind: Service
metadata:
  labels:
    app: infinispan
  name: infinispan-server
spec:
  ports:
  - port: 11222
    targetPort: 11222
    name: hotrod
  - port: 9990
    targetPort: 9990
    name: management
  selector:
    name: infinispan-server
    app: infinispan
---
kind: Secret
apiVersion: v1
metadata:
  name: infinispan
type: Opaque
stringData:
  application.username: app
  application.password: test12
  management.username: admin
  management.password: test1234
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  labels:
    name: infinispan-server
    app: infinispan
  name: infinispan-server
spec:
  replicas: 1
  serviceName: infinispan-server-headless
  selector:
    matchLabels:
      name: infinispan-server
      app: infinispan
  template:
    metadata:
      labels:
        name: infinispan-server
        app: infinispan
      name: infinispan-server
    spec:
      serviceAccount: infinispan
      containers:
      - args:
        - cloud
        - -Djboss.default.jgroups.stack=kubernetes
        env:
        - name: KUBERNETES_LABELS
          value: app=infinispan,name=infinispan-server
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_USER
          valueFrom:
            secretKeyRef:
              name: infinispan
              key: application.username
        - name: APP_PASS
          valueFrom:
            secretKeyRef:
              name: infinispan
              key: application.password
        - name: MGMT_USER
          valueFrom:
            secretKeyRef:
              name: infinispan
              key: management.username
        - name: MGMT_PASS
          valueFrom:
            secretKeyRef:
              name: infinispan
              key: management.password
        image: jboss/infinispan-server:9.4.11.Final
        name: infinispan-server
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9990
          name: management
          protocol: TCP
        - containerPort: 8888
          name: ping
          protocol: TCP
        - containerPort: 11222
          name: hotrod
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/is_running.sh
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 80
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/is_healthy.sh
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 80
        resources:
          requests:
            cpu: "0.5"
            memory: 512Mi
      terminationGracePeriodSeconds: 120
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infinispan
  labels:
    app: infinispan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: infinispan
  name: iot.enmasse.io:infinispan
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infinispan
  labels:
    app: infinispan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iot.enmasse.io:infinispan
subjects:
- kind: ServiceAccount
  name: infinispan
  namespace: ${NAMESPACE}
