---
apiVersion: v1
kind: Service
metadata:
  name: iot-auth-service
  labels:
    app: iot-core
    component: iot-auth-service
    enmasse-component: iot
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: iot-auth-service-tls
spec:
  ports:
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: 5671
  selector:
    app: iot-core
    component: iot-auth-service
