---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: iot-auth-service
  labels:
    app: iot-core
    component: iot-auth-service
    enmasse-component: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-core
      component: iot-auth-service
  template:
    metadata:
      labels:
        app: iot-core
        component: iot-auth-service
        enmasse-component: iot
    spec:
      containers:
      - name: auth-service
        image: ${IOT_AUTH_SERVICE_IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:///etc/config/
        - name: SPRING_PROFILES_ACTIVE
          value: authentication-impl
        - name: LOGGING_CONFIG
          value: file:///etc/config/logback-spring.xml
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 180
        resources:
          limits:
            memory: 512Mi
        ports:
        - containerPort: 8778
          name: jolokia
        - containerPort: 5671
          name: amqps
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/config
          name: conf
        - mountPath: /etc/tls
          name: tls
          readOnly: true
      volumes:
      - name: conf
        configMap:
          name: iot-auth-service-config
      - name: tls
        secret:
          secretName: iot-auth-service-tls
