---
enmasse_tmp_dir: '/tmp/enmasse/'
# vars for clients tasks
systemtests_dir: "{{ playbook_dir }}../../../"
client_executable_folder: "{{ systemtests_dir }}/client_executable"
rhea_path: "{{ client_executable_folder }}/rhea"
cli_qpid_jms_url: "https://github.com/rh-messaging/cli-java/releases/download/v2.3.0er1/cli-qpid-jms-1.2.2-SNAPSHOT-0.40.0.redhat-00001.jar"
cli_activemq_url: "https://github.com/rh-messaging/cli-java/releases/download/v2.3.0er1/cli-activemq-1.2.2-SNAPSHOT-5.11.0.redhat-630371.jar"
cli_artemis_url: "https://github.com/rh-messaging/cli-java/releases/download/v2.3.0er1/cli-artemis-jms-1.2.2-SNAPSHOT-2.6.3.redhat-00015.jar"

# vars for dependencies tasks
nodejs_version: "6"
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"
