apiVersion: v1
kind: Service
metadata:
  name: prometheus
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: prometheus-proxy-cert
  labels:
    app: enmasse
spec:
  ports:
  - name: proxy
    port: 443
    targetPort: 8443
  selector:
    name: prometheus