name: Master build
env:
  TAG: "latest"
  DOCKER_ORG: enmasse
  KUBERNETES_NAMESPACE: "enmasse-infra"
  REGISTRY_USER: "enmasse+ci"

on:
  schedule:
    - cron:  '0 */2 * * *'

jobs:
  smoke:
    strategy:
      matrix:
        refs: [refs/heads/master]
    name: Smoke tests and Release

    env:
      DOCKER_REGISTRY: "quay.io"
      TAG: "latest"
      PUSH_REGISTRY: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Clean disk
        run: ./.github/scripts/clean_disk.sh

      - name: Set version
        id: version
        run: |
          echo "::set-env name=VERSION::$(grep "release.version" pom.properties| cut -d'=' -f2)"
          echo "::set-output name=VERSION::$(grep "release.version" pom.properties| cut -d'=' -f2)"

      - name: Install dependencies
        run: ./.github/scripts/install_dep.sh

      - uses: actions/setup-go@v2
        with:
          go-version: '1.13.1'
      - run: go version

      - name: setup-docker
        run: ./.github/scripts/setup_docker.sh

      - name: Minikube setup with registry
        uses: EnMasseProject/minikube-setup@V1.0.2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.2

      - name: Setup OLM
        run: ./.github/scripts/setup-olm.sh

      - name: Build
        id: build
        run: |
          export REGISTRY_PASS=${{ secrets.REGISTRY_PASS }}
          ./.github/scripts/build.sh

      - name: Smoke tests
        run: ./.github/scripts/smoke_test.sh

      - name: OLM tests
        run: ./.github/scripts/olm_test.sh

      - name: Collect logs
        if: failure()
        run: ./.github/scripts/collectLogs.sh

      - name: Checkout docs repository
        uses: actions/checkout@v2
        with:
          repository: enmasseproject/enmasseproject.github.io
          ref: master
          path: website

      - name: Copy documentation
        env:
          FROM: .
          TO: website
        run: ./.github/scripts/copy_docs.sh

      - name: Publish documentation
        uses: ad-m/github-push-action@master
        with:
          repository: enmasseproject/enmasseproject.github.io
          branch: master
          directory: website
          github_token: ${{ secrets.CI_TOKEN }}

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: smoke-test-logs
          path: test-logs.zip


