name: PR job
env:
  DOCKER_REGISTRY: "localhost:5000"
  TAG: "latest"
  IMAGE_PULL_POLICY: "IfNotPresent"
  DOCKER_ORG: enmasse
  KUBERNETES_NAMESPACE: "enmasse-infra"

on: [pull_request]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set version
        run: |
          echo "::set-env name=VERSION::$(grep "release.version" pom.properties| cut -d'=' -f2)"

      - name: Install dependencies
        run: ./.github/scripts/install_dep.sh

      - uses: actions/setup-go@v2
        with:
          go-version: '1.13.1'

      - run: go version

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.2

      - name: Unit tests and build
        run: make

  systemtests:
    env:
      SKIP_TESTS: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Clean disk
        run: ./.github/scripts/clean_disk.sh

      - name: Set version
        run: |
          echo "::set-env name=VERSION::$(grep "release.version" pom.properties| cut -d'=' -f2)"

      - name: Install dependencies
        run: ./.github/scripts/install_dep.sh

      - uses: actions/setup-go@v2
        with:
          go-version: '1.13.1'
      - run: go version

      - name: setup-docker
        run: ./.github/scripts/setup_docker.sh

      - name: setup-kind
        run: ./.github/scripts/setup_kind.sh

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.2

      - name: Setup OLM
        run: ./.github/scripts/setup-olm.sh

      - name: Build images
        run: ./.github/scripts/build.sh

      - name: Smoke tests
        run: ./.github/scripts/smoke_test.sh

      - name: OLM tests
        run: ./.github/scripts/olm_test.sh

      - name: Collect logs
        if: failure()
        run: ./.github/scripts/collectLogs.sh

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: smoke-test-logs
          path: test-logs.zip
